import type { Metadata } from "next";
import localFont from "next/font/local";
import {IBM_Plex_Sans as FontSans} from "next/font/google"
import "./globals.css";
import {cn} from "@/lib/utils"
import Header from "@/components/home/header";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const fontSans= FontSans({subsets: ["latin"],
   weight:["400","500","600","700"],
   variable: "--font-sans"
  })

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header/>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
